<!-- 
This page is for non authenticated users. It is a copy of Audio.vue
 -->

<template>
    <!-- Main Audio 'card'.  -->
  <div class="w-screen h-screen lg:h-auto lg:w-auto relative bg-gradient-to-b from-blue-400 to-blue-100 p-8 flex flex-col items-center rounded-lg drop-shadow-lg">
    <div class="text-center mt-8 lg:mt-2">
      <p class="text-5xl lg:text-xl font-bold">Book of Mormon</p>
      <p class="text-2xl lg:text-lg font-semibold mb-2">Thorderson Family</p>
    </div>
    <img
      class="rounded-full h-80 w-80 lg:h-40 lg:w-40"
      :src="currentImage"
      alt="narratorImageName no image"
    />
    <div class="flex flex-col items-center mt-4 mx-2 c text-4xl lg:text-lg text-black font-bold">
      {{ selectedReader.narrator }}
    </div>
    <div class="flex flex-col items-center text-black text-3xl lg:text-lg font-semibold">
      {{ selectedReader.book }}
      {{ selectedReader.chapter }}
    </div>
    <div class="container">
      <div class="flex justify-around mt-8 lg:mt-0 items-center mb-2 h-20">
        <button
          type="button"
          @click="prev"
        >
          <icon name="prev"></icon>
        </button>
        <button
          type="button"
          @click="play"
          v-if="!isPlaying"
        >
          <icon name="play"></icon>
        </button>
        <button
          type="button"
          @click="pause"
          v-else
        >
          <icon name="pause"></icon>
        </button>
        <button
          type="button"
          @click="next"
        >
          <icon name="next"></icon>
        </button>
      </div>
      <div class="container mt-4">
        <div
          class="
            relative
            container
            flex flex-col
            objects-center
            mt-4
          "
        >
          <div class="flex flex-1 flex-col items-center space-x-1 mt-8 lg:mt-0">
            <input
              type="range"
              max="100"
              id="progressBar"
              v-model="audio.currentTime"
              class="cursor-pointer w-3/4"
            />
            <div class="flex justify-between font-semibold text-black text-3xl lg:text-lg mt-4">
              <span>{{ currentTimeTxt }} / {{ currentDurationTxt }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { useReaderStore } from "../stores/Readers";
import Tab2 from "./Tab2.vue";
import { ref } from "vue";
import axios from "axios";
import { router } from '@inertiajs/vue3';
import { computed } from "vue";
import { usePage } from "@inertiajs/vue3";
// import { usePage } from "@inertiajs/inertia-vue3";

export default {
  props: ["newReader"],
  data() {
    return {
      audio: new Audio(),
      isPlaying: false,
      currentReader: {}, //this will be related to the User
      currentNarrator: "",
      currentImage: "",
      progressBar: {},
      currentDuration: 0,
      currentTime: 0,
      currentTimeTxt: "0:00",
      currentDurationTxt: "0:00",
      index: 5, //1 Nephi 1
      volume: 80,
      isMuted: false,
      isMaxed: false,
      pictureHasChanged: false,
      selectedReader: useReaderStore(),

    readers: [
        {
          uuid: 1,
          bookID: 1,
          book: "Intro",
          chapter: 1,
          narrator: "Carol",
          narratorImageName: "Carol",
          chapterImageName: "Intro1",
          audioFileName: "Intro1",
          isActiveBookmark: false,
          src: "assets/media/Intro1.mp3",
        },
        {
          uuid: 2,
          bookID: 1,
          book: "Intro",
          chapter: 2,
          narrator: "Carol",
          narratorImageName: "Carol",
          chapterImageName: "Intro2",
          audioFileName: "Intro2",
          isActiveBookmark: false,
          src: "assets/media/Intro2.mp3",
        },
        {
          uuid: 3,
          bookID: 1,
          book: "Intro",
          chapter: 3,
          narrator: "Carol",
          narratorImageName: "Carol",
          chapterImageName: "Intro3",
          audioFileName: "Intro3",
          isActiveBookmark: false,
          src: "assets/media/Intro3.mp3",
        },
        {
          uuid: 4,
          bookID: 1,
          book: "Intro",
          chapter: 4,
          narrator: "Carol",
          narratorImageName: "Carol",
          chapterImageName: "Intro4",
          audioFileName: "Intro4",
          isActiveBookmark: false,
          src: "assets/media/Intro4.mp3",
        },
        {
          uuid: 5,
          bookID: 1,
          book: "Intro",
          chapter: 5,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "Intro5",
          audioFileName: "Intro5",
          isActiveBookmark: false,
          src: "assets/media/Intro5.mp3",
        },
        {
          uuid: 6,
          bookID: 2,
          book: "1 Nephi",
          chapter: 1,
          narrator: "Carol",
          narratorImageName: "Carol",
          chapterImageName: "1Nephi1",
          audioFileName: "1Nephi1",
          isActiveBookmark: false,
          src: "assets/media/1Nephi1.mp3",
        },
        {
          uuid: 7,
          bookID: 2,
          book: "1 Nephi",
          chapter: 2,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "1Nephi2",
          audioFileName: "1Nephi2",
          isActiveBookmark: false,
          src: "assets/media/1Nephi2.mp3",
        },
        {
          uuid: 8,
          bookID: 2,
          book: "1 Nephi",
          chapter: 3,
          narrator: "Ali",
          narratorImageName: "Ali",
          chapterImageName: "1Nephi3",
          audioFileName: "1Nephi3",
          isActiveBookmark: false,
          src: "assets/media/1Nephi3.mp3",
        },
        {
          uuid: 9,
          bookID: 2,
          book: "1 Nephi",
          chapter: 4,
          narrator: "Ali",
          narratorImageName: "Ali",
          chapterImageName: "1Nephi4",
          audioFileName: "1Nephi4",
          isActiveBookmark: false,
          src: "assets/media/1Nephi4.mp3",
        },
        {
          uuid: 10,
          bookID: 2,
          book: "1 Nephi",
          chapter: 5,
          narrator: "Ali",
          narratorImageName: "Ali",
          chapterImageName: "1Nephi5",
          audioFileName: "1Nephi5",
          isActiveBookmark: false,
          src: "assets/media/1Nephi5.mp3",
        },
        {
          uuid: 11,
          bookID: 2,
          book: "1 Nephi",
          chapter: 6,
          narrator: "Benn",
          narratorImageName: "Benn",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi6",
          isActiveBookmark: false,
          src: "assets/media/1Nephi6.mp3",
        },
        {
          uuid: 12,
          bookID: 2,
          book: "1 Nephi",
          chapter: 7,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi7",
          isActiveBookmark: false,
          src: "assets/media/1Nephi7.mp3",
        },
        {
          uuid: 13,
          bookID: 2,
          book: "1 Nephi",
          chapter: 8,
          narrator: "Lucie",
          narratorImageName: "Lucie",
          chapterImageName: "1Nephi8",
          audioFileName: "1Nephi8",
          isActiveBookmark: false,
          src: "assets/media/1Nephi8.mp3",
        },
        {
          uuid: 14,
          bookID: 2,
          book: "1 Nephi",
          chapter: 9,
          narrator: "Lucie",
          narratorImageName: "Lucie",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi9",
          isActiveBookmark: false,
          src: "assets/media/1Nephi9.mp3",
        },
        {
          uuid: 15,
          bookID: 2,
          book: "1 Nephi",
          chapter: 10,
          narrator: "James",
          narratorImageName: "James",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi10",
          isActiveBookmark: false,
          src: "assets/media/1Nephi10.mp3",
        },
        {
          uuid: 16,
          bookID: 2,
          book: "1 Nephi",
          chapter: 11,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "1Nephi11",
          audioFileName: "1Nephi11",
          isActiveBookmark: false,
          src: "assets/media/1Nephi11.mp3",
        },
        {
          uuid: 17,
          bookID: 2,
          book: "1 Nephi",
          chapter: 12,
          narrator: "Kate",
          narratorImageName: "Kate",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi12",
          isActiveBookmark: false,
          src: "assets/media/1Nephi12.mp3",
        },
        {
          uuid: 18,
          bookID: 2,
          book: "1 Nephi",
          chapter: 13,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "1Nephi13",
          audioFileName: "1Nephi13",
          isActiveBookmark: false,
          src: "assets/media/1Nephi13.mp3",
        },
        {
          uuid: 19,
          bookID: 2,
          book: "1 Nephi",
          chapter: 14,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi14",
          isActiveBookmark: false,
          src: "assets/media/1Nephi14.mp3",
        },
        {
          uuid: 20,
          bookID: 2,
          book: "1 Nephi",
          chapter: 15,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi15",
          isActiveBookmark: false,
          src: "assets/media/1Nephi15.mp3",
        },
        {
          uuid: 21,
          bookID: 2,
          book: "1 Nephi",
          chapter: 16,
          narrator: "Chloe",
          narratorImageName: "Chloe",
          chapterImageName: "1Nephi16",
          audioFileName: "1Nephi16",
          isActiveBookmark: false,
          src: "assets/media/1Nephi16.mp3",
        },
        {
          uuid: 22,
          bookID: 2,
          book: "1 Nephi",
          chapter: 17,
          narrator: "Nate",
          narratorImageName: "Nate",
          chapterImageName: "1Nephi17",
          audioFileName: "1Nephi17",
          isActiveBookmark: false,
          src: "assets/media/1Nephi17.mp3",
        },
        {
          uuid: 23,
          bookID: 2,
          book: "1 Nephi",
          chapter: 18,
          narrator: "Mya",
          narratorImageName: "Mya",
          chapterImageName: "1Nephi18",
          audioFileName: "1Nephi18",
          isActiveBookmark: false,
          src: "assets/media/1Nephi18.mp3",
        },
        {
          uuid: 24,
          bookID: 2,
          book: "1 Nephi",
          chapter: 19,
          narrator: "Will",
          narratorImageName: "Will",
          chapterImageName: "1Nephi19",
          audioFileName: "1Nephi19",
          isActiveBookmark: false,
          src: "assets/media/1Nephi19.mp3",
        },
        {
          uuid: 25,
          bookID: 2,
          book: "1 Nephi",
          chapter: 20,
          narrator: "Melissa",
          narratorImageName: "Melissa",
          chapterImageName: "1Nephi20",
          audioFileName: "1Nephi20",
          isActiveBookmark: false,
          src: "assets/media/1Nephi20.mp3",
        },
        {
          uuid: 26,
          bookID: 2,
          book: "1 Nephi",
          chapter: 21,
          narrator: "Nels",
          narratorImageName: "Nels",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi21",
          isActiveBookmark: false,
          src: "assets/media/1Nephi21.mp3",
        },
        {
          uuid: 27,
          bookID: 2,
          book: "1 Nephi",
          chapter: 22,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "1Nephi22",
          isActiveBookmark: false,
          src: "assets/media/1Nephi22.mp3",
        },
        {
          uuid: 28,
          bookID: 3,
          book: "2 Nephi",
          chapter: 1,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "2Nephi1",
          audioFileName: "2Nephi1",
          isActiveBookmark: false,
          src: "assets/media/2Nephi1.mp3",
        },
        {
          uuid: 29,
          bookID: 3,
          book: "2 Nephi",
          chapter: 2,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "2Nephi2",
          audioFileName: "2Nephi2",
          isActiveBookmark: false,
          src: "assets/media/2Nephi2.mp3",
        },
        {
          uuid: 30,
          bookID: 3,
          book: "2 Nephi",
          chapter: 3,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "2Nephi3",
          audioFileName: "2Nephi3",
          isActiveBookmark: false,
          src: "assets/media/2Nephi3.mp3",
        },
        {
          uuid: 31,
          bookID: 3,
          book: "2 Nephi",
          chapter: 4,
          narrator: "Julie T",
          narratorImageName: "JulieT",
          chapterImageName: "2Nephi4",
          audioFileName: "2Nephi4",
          isActiveBookmark: false,
          src: "assets/media/2Nephi4.mp3",
        },
        {
          uuid: 32,
          bookID: 3,
          book: "2 Nephi",
          chapter: 5,
          narrator: "Carley",
          narratorImageName: "Carley",
          chapterImageName: "2Nephi5",
          audioFileName: "2Nephi5",
          isActiveBookmark: false,
          src: "assets/media/2Nephi5.mp3",
        },
        {
          uuid: 33,
          bookID: 3,
          book: "2 Nephi",
          chapter: 6,
          narrator: "Alan",
          narratorImageName: "Alan",
          chapterImageName: "2Nephi6",
          audioFileName: "2Nephi6",
          isActiveBookmark: false,
          src: "assets/media/2Nephi6.mp3",
        },
        {
          uuid: 34,
          bookID: 3,
          book: "2 Nephi",
          chapter: 7,
          narrator: "Britta",
          narratorImageName: "Britta",
          chapterImageName: "2Nephi7",
          audioFileName: "2Nephi7",
          isActiveBookmark: false,
          src: "assets/media/2Nephi7.mp3",
        },
        {
          uuid: 35,
          bookID: 3,
          book: "2 Nephi",
          chapter: 8,
          narrator: "Anika",
          narratorImageName: "Anika",
          chapterImageName: "2Nephi8",
          audioFileName: "2Nephi8",
          isActiveBookmark: false,
          src: "assets/media/2Nephi8.mp3",
        },
        {
          uuid: 36,
          bookID: 3,
          book: "2 Nephi",
          chapter: 9,
          narrator: "Nels",
          narratorImageName: "Nels",
          chapterImageName: "2Nephi9",
          audioFileName: "2Nephi9",
          isActiveBookmark: false,
          src: "assets/media/2Nephi9.mp3",
        },
        {
          uuid: 37,
          bookID: 3,
          book: "2 Nephi",
          chapter: 10,
          narrator: "Mitchell",
          narratorImageName: "Mitchell",
          chapterImageName: "2Nephi10",
          audioFileName: "2Nephi10",
          isActiveBookmark: false,
          src: "assets/media/2Nephi10.mp3",
        },
        {
          uuid: 38,
          bookID: 3,
          book: "2 Nephi",
          chapter: 11,
          narrator: "Abby",
          narratorImageName: "Abby",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi11",
          isActiveBookmark: false,
          src: "assets/media/2Nephi11.mp3",
        },
        {
          uuid: 39,
          bookID: 3,
          book: "2 Nephi",
          chapter: 12,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi12",
          isActiveBookmark: false,
          src: "assets/media/2Nephi12.mp3",
        },
        {
          uuid: 40,
          bookID: 3,
          book: "2 Nephi",
          chapter: 13,
          narrator: "Susan",
          narratorImageName: "Susan",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi13",
          isActiveBookmark: false,
          src: "assets/media/2Nephi13.mp3",
        },
        {
          uuid: 41,
          bookID: 3,
          book: "2 Nephi",
          chapter: 14,
          narrator: "Sully",
          narratorImageName: "Sully",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi14",
          isActiveBookmark: false,
          src: "assets/media/2Nephi14.mp3",
        },
        {
          uuid: 42,
          bookID: 3,
          book: "2 Nephi",
          chapter: 15,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi15",
          isActiveBookmark: false,
          src: "assets/media/2Nephi15.mp3",
        },
        {
          uuid: 43,
          bookID: 3,
          book: "2 Nephi",
          chapter: 16,
          narrator: "Benn",
          narratorImageName: "Benn",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi16",
          isActiveBookmark: false,
          src: "assets/media/2Nephi16.mp3",
        },
        {
          uuid: 44,
          bookID: 3,
          book: "2 Nephi",
          chapter: 17,
          narrator: "Lars",
          narratorImageName: "Lars",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi17",
          isActiveBookmark: false,
          src: "assets/media/2Nephi17.mp3",
        },
        {
          uuid: 45,
          bookID: 3,
          book: "2 Nephi",
          chapter: 18,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi18",
          isActiveBookmark: false,
          src: "assets/media/2Nephi18.mp3",
        },
        {
          uuid: 46,
          bookID: 3,
          book: "2 Nephi",
          chapter: 19,
          narrator: "Greta",
          narratorImageName: "Greta",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi19",
          isActiveBookmark: false,
          src: "assets/media/2Nephi19.mp3",
        },
        {
          uuid: 47,
          bookID: 3,
          book: "2 Nephi",
          chapter: 20,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi20",
          isActiveBookmark: false,
          src: "assets/media/2Nephi20.mp3",
        },
        {
          uuid: 48,
          bookID: 3,
          book: "2 Nephi",
          chapter: 21,
          narrator: "Susan",
          narratorImageName: "Susan",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi21",
          isActiveBookmark: false,
          src: "assets/media/2Nephi21.mp3",
        },
        {
          uuid: 49,
          bookID: 3,
          book: "2 Nephi",
          chapter: 22,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi22",
          isActiveBookmark: false,
          src: "assets/media/2Nephi22.mp3",
        },
        {
          uuid: 50,
          bookID: 3,
          book: "2 Nephi",
          chapter: 23,
          narrator: "Will",
          narratorImageName: "Will",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi23",
          isActiveBookmark: false,
          src: "assets/media/2Nephi23.mp3",
        },
        {
          uuid: 51,
          bookID: 3,
          book: "2 Nephi",
          chapter: 24,
          narrator: "Eric",
          narratorImageName: "Eric",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi24",
          isActiveBookmark: false,
          src: "assets/media/2Nephi24.mp3",
        },
        {
          uuid: 52,
          bookID: 3,
          book: "2 Nephi",
          chapter: 25,
          narrator: "Scot",
          narratorImageName: "Scot",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi25",
          isActiveBookmark: false,
          src: "assets/media/2Nephi25.mp3",
        },
        {
          uuid: 53,
          bookID: 3,
          book: "2 Nephi",
          chapter: 26,
          narrator: "Nate",
          narratorImageName: "Nate",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi26",
          isActiveBookmark: false,
          src: "assets/media/2Nephi26.mp3",
        },
        {
          uuid: 54,
          bookID: 3,
          book: "2 Nephi",
          chapter: 27,
          narrator: "Britta",
          narratorImageName: "Britta",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi27",
          isActiveBookmark: false,
          src: "assets/media/2Nephi27.mp3",
        },
        {
          uuid: 55,
          bookID: 3,
          book: "2 Nephi",
          chapter: 28,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi28",
          isActiveBookmark: false,
          src: "assets/media/2Nephi28.mp3",
        },
        {
          uuid: 56,
          bookID: 3,
          book: "2 Nephi",
          chapter: 29,
          narrator: "Maren",
          narratorImageName: "Maren",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi29",
          isActiveBookmark: false,
          src: "assets/media/2Nephi29.mp3",
        },
        {
          uuid: 57,
          bookID: 3,
          book: "2 Nephi",
          chapter: 30,
          narrator: "Brinton",
          narratorImageName: "Brinton",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi30",
          isActiveBookmark: false,
          src: "assets/media/2Nephi30.mp3",
        },
        {
          uuid: 58,
          bookID: 3,
          book: "2 Nephi",
          chapter: 31,
          narrator: "Julie W",
          narratorImageName: "JulieW",
          chapterImageName: "2Nephi31",
          audioFileName: "2Nephi31",
          isActiveBookmark: false,
          src: "assets/media/2Nephi31.mp3",
        },
        {
          uuid: 59,
          bookID: 3,
          book: "2 Nephi",
          chapter: 32,
          narrator: "Julie W",
          narratorImageName: "JulieW",
          chapterImageName: "2Nephi32",
          audioFileName: "2Nephi32",
          isActiveBookmark: false,
          src: "assets/media/2Nephi32.mp3",
        },
        {
          uuid: 60,
          bookID: 3,
          book: "2 Nephi",
          chapter: 33,
          narrator: "Julie W",
          narratorImageName: "JulieW",
          chapterImageName: "BOMpic",
          audioFileName: "2Nephi33",
          isActiveBookmark: false,
          src: "assets/media/2Nephi33.mp3",
        },
        {
          uuid: 61,
          bookID: 4,
          book: "Jacob",
          chapter: 1,
          narrator: "Dugan",
          narratorImageName: "Dugan",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob1",
          isActiveBookmark: false,
          src: "assets/media/Jacob1.mp3",
        },
        {
          uuid: 62,
          bookID: 4,
          book: "Jacob",
          chapter: 2,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob2",
          isActiveBookmark: false,
          src: "assets/media/Jacob2.mp3",
        },
        {
          uuid: 63,
          bookID: 4,
          book: "Jacob",
          chapter: 3,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob3",
          isActiveBookmark: false,
          src: "assets/media/Jacob3.mp3",
        },
        {
          uuid: 64,
          bookID: 4,
          book: "Jacob",
          chapter: 4,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob4",
          isActiveBookmark: false,
          src: "assets/media/Jacob4.mp3",
        },
        {
          uuid: 65,
          bookID: 4,
          book: "Jacob",
          chapter: 5,
          narrator: "Susan",
          narratorImageName: "Susan",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob5",
          isActiveBookmark: false,
          src: "assets/media/Jacob5.mp3",
        },
        {
          uuid: 66,
          bookID: 4,
          book: "Jacob",
          chapter: 6,
          narrator: "Sara",
          narratorImageName: "Sara",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob6",
          isActiveBookmark: false,
          src: "assets/media/Jacob6.mp3",
        },
        {
          uuid: 67,
          bookID: 4,
          book: "Jacob",
          chapter: 7,
          narrator: "Chloe",
          narratorImageName: "Chloe",
          chapterImageName: "BOMpic",
          audioFileName: "Jacob7",
          isActiveBookmark: false,
          src: "assets/media/Jacob7.mp3",
        },
        {
          uuid: 68,
          bookID: 5,
          book: "Enos",
          chapter: 1,
          narrator: "Lars",
          narratorImageName: "Lars",
          chapterImageName: "BOMpic",
          audioFileName: "Enos1",
          isActiveBookmark: false,
          src: "assets/media/Enos1.mp3",
        },
        {
          uuid: 69,
          bookID: 6,
          book: "Jarom",
          chapter: 1,
          narrator: "Nate",
          narratorImageName: "Nate",
          chapterImageName: "BOMpic",
          audioFileName: "Jarom1",
          isActiveBookmark: false,
          src: "assets/media/Jarom1.mp3",
        },
        {
          uuid: 70,
          bookID: 7,
          book: "Omni",
          chapter: 1,
          narrator: "Mitchell",
          narratorImageName: "Mitchell",
          chapterImageName: "Omni1",
          audioFileName: "Omni1",
          isActiveBookmark: false,
          src: "assets/media/Omni1.mp3",
        },
        {
          uuid: 71,
          bookID: 8,
          book: "Words of Mormon",
          chapter: 1,
          narrator: "Dugan",
          narratorImageName: "Dugan",
          chapterImageName: "WordsOfMormon1",
          audioFileName: "WordsOfMormon1",
          isActiveBookmark: false,
          src: "assets/media/WordsOfMormon1.mp3",
        },
        {
          uuid: 72,
          bookID: 9,
          book: "Mosiah",
          chapter: 1,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "Mosiah1",
          audioFileName: "Mosiah1",
          isActiveBookmark: false,
          src: "assets/media/Mosiah1.mp3",
        },
        {
          uuid: 73,
          bookID: 9,
          book: "Mosiah",
          chapter: 2,
          narrator: "Julie T",
          narratorImageName: "JulieT",
          chapterImageName: "Mosiah2",
          audioFileName: "Mosiah2",
          isActiveBookmark: false,
          src: "assets/media/Mosiah2.mp3",
        },
        {
          uuid: 74,
          bookID: 9,
          book: "Mosiah",
          chapter: 3,
          narrator: "Julie T",
          narratorImageName: "JulieT",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah3",
          isActiveBookmark: false,
          src: "assets/media/Mosiah3.mp3",
        },
        {
          uuid: 75,
          bookID: 9,
          book: "Mosiah",
          chapter: 4,
          narrator: "Julie T",
          narratorImageName: "JulieT",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah4",
          isActiveBookmark: false,
          src: "assets/media/Mosiah4.mp3",
        },
        {
          uuid: 76,
          bookID: 9,
          book: "Mosiah",
          chapter: 5,
          narrator: "Maren",
          narratorImageName: "Maren",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah5",
          isActiveBookmark: false,
          src: "assets/media/Mosiah5.mp3",
        },
        {
          uuid: 77,
          bookID: 9,
          book: "Mosiah",
          chapter: 6,
          narrator: "Kate",
          narratorImageName: "Kate",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah6",
          isActiveBookmark: false,
          src: "assets/media/Mosiah6.mp3",
        },
        {
          uuid: 78,
          bookID: 9,
          book: "Mosiah",
          chapter: 7,
          narrator: "Brinton",
          narratorImageName: "Brinton",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah7",
          isActiveBookmark: false,
          src: "assets/media/Mosiah7.mp3",
        },
        {
          uuid: 79,
          bookID: 9,
          book: "Mosiah",
          chapter: 8,
          narrator: "Brinton",
          narratorImageName: "Brinton",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah8",
          isActiveBookmark: false,
          src: "assets/media/Mosiah8.mp3",
        },
        {
          uuid: 80,
          bookID: 9,
          book: "Mosiah",
          chapter: 9,
          narrator: "Mitchell",
          narratorImageName: "Mitchell",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah9",
          isActiveBookmark: false,
          src: "assets/media/Mosiah9.mp3",
        },
        {
          uuid: 81,
          bookID: 9,
          book: "Mosiah",
          chapter: 10,
          narrator: "Mitchell",
          narratorImageName: "Mitchell",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah10",
          isActiveBookmark: false,
          src: "assets/media/Mosiah10.mp3",
        },
        {
          uuid: 82,
          bookID: 9,
          book: "Mosiah",
          chapter: 11,
          narrator: "Mitchell",
          narratorImageName: "Mitchell",
          chapterImageName: "Mosiah11",
          audioFileName: "Mosiah11",
          isActiveBookmark: false,
          src: "assets/media/Mosiah11.mp3",
        },
        {
          uuid: 83,
          bookID: 9,
          book: "Mosiah",
          chapter: 12,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah12",
          isActiveBookmark: false,
          src: "assets/media/Mosiah12.mp3",
        },
        {
          uuid: 84,
          bookID: 9,
          book: "Mosiah",
          chapter: 13,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "Mosiah13",
          audioFileName: "Mosiah13",
          isActiveBookmark: false,
          src: "assets/media/Mosiah13.mp3",
        },
        {
          uuid: 85,
          bookID: 9,
          book: "Mosiah",
          chapter: 14,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah14",
          isActiveBookmark: false,
          src: "assets/media/Mosiah14.mp3",
        },
        {
          uuid: 86,
          bookID: 9,
          book: "Mosiah",
          chapter: 15,
          narrator: "Alan",
          narratorImageName: "Alan",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah15",
          isActiveBookmark: false,
          src: "assets/media/Mosiah15.mp3",
        },
        {
          uuid: 87,
          bookID: 9,
          book: "Mosiah",
          chapter: 16,
          narrator: "Benn",
          narratorImageName: "Benn",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah16",
          isActiveBookmark: false,
          src: "assets/media/Mosiah16.mp3",
        },
        {
          uuid: 88,
          bookID: 9,
          book: "Mosiah",
          chapter: 17,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah17",
          isActiveBookmark: false,
          src: "assets/media/Mosiah17.mp3",
        },
        {
          uuid: 89,
          bookID: 9,
          book: "Mosiah",
          chapter: 18,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "Mosiah18",
          audioFileName: "Mosiah18",
          isActiveBookmark: false,
          src: "assets/media/Mosiah18.mp3",
        },
        {
          uuid: 90,
          bookID: 9,
          book: "Mosiah",
          chapter: 19,
          narrator: "James",
          narratorImageName: "James",
          chapterImageName: "Mosiah19",
          audioFileName: "Mosiah19",
          isActiveBookmark: false,
          src: "assets/media/Mosiah19.mp3",
        },
        {
          uuid: 91,
          bookID: 9,
          book: "Mosiah",
          chapter: 20,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah20",
          isActiveBookmark: false,
          src: "assets/media/Mosiah20.mp3",
        },
        {
          uuid: 92,
          bookID: 9,
          book: "Mosiah",
          chapter: 21,
          narrator: "Chloe",
          narratorImageName: "Chloe",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah21",
          isActiveBookmark: false,
          src: "assets/media/Mosiah21.mp3",
        },
        {
          uuid: 93,
          bookID: 9,
          book: "Mosiah",
          chapter: 22,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "Mosiah22",
          audioFileName: "Mosiah22",
          isActiveBookmark: false,
          src: "assets/media/Mosiah22.mp3",
        },
        {
          uuid: 94,
          bookID: 9,
          book: "Mosiah",
          chapter: 23,
          narrator: "Sadie",
          narratorImageName: "Sadie",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah23",
          isActiveBookmark: false,
          src: "assets/media/Mosiah23.mp3",
        },
        {
          uuid: 95,
          bookID: 9,
          book: "Mosiah",
          chapter: 24,
          narrator: "Sadie",
          narratorImageName: "Sadie",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah24",
          isActiveBookmark: false,
          src: "assets/media/Mosiah24.mp3",
        },
        {
          uuid: 96,
          bookID: 9,
          book: "Mosiah",
          chapter: 25,
          narrator: "Sadie",
          narratorImageName: "Sadie",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah25",
          isActiveBookmark: false,
          src: "assets/media/Mosiah25.mp3",
        },
        {
          uuid: 97,
          bookID: 9,
          book: "Mosiah",
          chapter: 26,
          narrator: "Abby",
          narratorImageName: "Abby",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah26",
          isActiveBookmark: false,
          src: "assets/media/Mosiah26.mp3",
        },
        {
          uuid: 98,
          bookID: 9,
          book: "Mosiah",
          chapter: 27,
          narrator: "Anika",
          narratorImageName: "Anika",
          chapterImageName: "Mosiah27",
          audioFileName: "Mosiah27",
          isActiveBookmark: false,
          src: "assets/media/Mosiah27.mp3",
        },
        {
          uuid: 99,
          bookID: 9,
          book: "Mosiah",
          chapter: 28,
          narrator: "Anika",
          narratorImageName: "Anika",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah28",
          isActiveBookmark: false,
          src: "assets/media/Mosiah28.mp3",
        },
        {
          uuid: 100,
          bookID: 9,
          book: "Mosiah",
          chapter: 29,
          narrator: "Anika",
          narratorImageName: "Anika",
          chapterImageName: "BOMpic",
          audioFileName: "Mosiah29",
          isActiveBookmark: false,
          src: "assets/media/Mosiah29.mp3",
        },
        {
          uuid: 101,
          bookID: 10,
          book: "Alma",
          chapter: 1,
          narrator: "Mya",
          narratorImageName: "Mya",
          chapterImageName: "BOMpic",
          audioFileName: "Alma1",
          isActiveBookmark: false,
          src: "assets/media/Alma1.mp3",
        },
        {
          uuid: 102,
          bookID: 10,
          book: "Alma",
          chapter: 2,
          narrator: "Carley",
          narratorImageName: "Carley",
          chapterImageName: "BOMpic",
          audioFileName: "Alma2",
          isActiveBookmark: false,
          src: "assets/media/Alma2.mp3",
        },
        {
          uuid: 103,
          bookID: 10,
          book: "Alma",
          chapter: 3,
          narrator: "Carley",
          narratorImageName: "Carley",
          chapterImageName: "BOMpic",
          audioFileName: "Alma3",
          isActiveBookmark: false,
          src: "assets/media/Alma3.mp3",
        },
        {
          uuid: 104,
          bookID: 10,
          book: "Alma",
          chapter: 4,
          narrator: "Sara",
          narratorImageName: "Sara",
          chapterImageName: "BOMpic",
          audioFileName: "Alma4",
          isActiveBookmark: false,
          src: "assets/media/Alma4.mp3",
        },
        {
          uuid: 105,
          bookID: 10,
          book: "Alma",
          chapter: 5,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "BOMpic",
          audioFileName: "Alma5",
          isActiveBookmark: false,
          src: "assets/media/Alma5.mp3",
        },
        {
          uuid: 106,
          bookID: 10,
          book: "Alma",
          chapter: 6,
          narrator: "Will",
          narratorImageName: "Will",
          chapterImageName: "BOMpic",
          audioFileName: "Alma6",
          isActiveBookmark: false,
          src: "assets/media/Alma6.mp3",
        },
        {
          uuid: 107,
          bookID: 10,
          book: "Alma",
          chapter: 7,
          narrator: "James",
          narratorImageName: "James",
          chapterImageName: "BOMpic",
          audioFileName: "Alma7",
          isActiveBookmark: false,
          src: "assets/media/Alma7.mp3",
        },
        {
          uuid: 108,
          bookID: 10,
          book: "Alma",
          chapter: 8,
          narrator: "Nels",
          narratorImageName: "Nels",
          chapterImageName: "BOMpic",
          audioFileName: "Alma8",
          isActiveBookmark: false,
          src: "assets/media/Alma8.mp3",
        },
        {
          uuid: 109,
          bookID: 10,
          book: "Alma",
          chapter: 9,
          narrator: "Nels",
          narratorImageName: "Nels",
          chapterImageName: "BOMpic",
          audioFileName: "Alma9",
          isActiveBookmark: false,
          src: "assets/media/Alma9.mp3",
        },
        {
          uuid: 110,
          bookID: 10,
          book: "Alma",
          chapter: 10,
          narrator: "Lars",
          narratorImageName: "Lars",
          chapterImageName: "BOMpic",
          audioFileName: "Alma10",
          isActiveBookmark: false,
          src: "assets/media/Alma10.mp3",
        },
        {
          uuid: 111,
          bookID: 10,
          book: "Alma",
          chapter: 11,
          narrator: "Lars",
          narratorImageName: "Lars",
          chapterImageName: "BOMpic",
          audioFileName: "Alma11",
          isActiveBookmark: false,
          src: "assets/media/Alma11.mp3",
        },
        {
          uuid: 112,
          bookID: 10,
          book: "Alma",
          chapter: 12,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "Alma12",
          isActiveBookmark: false,
          src: "assets/media/Alma12.mp3",
        },
        {
          uuid: 113,
          bookID: 10,
          book: "Alma",
          chapter: 13,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "Alma13",
          isActiveBookmark: false,
          src: "assets/media/Alma13.mp3",
        },
        {
          uuid: 114,
          bookID: 10,
          book: "Alma",
          chapter: 14,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "Alma14",
          audioFileName: "Alma14",
          isActiveBookmark: false,
          src: "assets/media/Alma14.mp3",
        },
        {
          uuid: 115,
          bookID: 10,
          book: "Alma",
          chapter: 15,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "BOMpic",
          audioFileName: "Alma15",
          isActiveBookmark: false,
          src: "assets/media/Alma15.mp3",
        },
        {
          uuid: 116,
          bookID: 10,
          book: "Alma",
          chapter: 16,
          narrator: "Greta",
          narratorImageName: "Greta",
          chapterImageName: "BOMpic",
          audioFileName: "Alma16",
          isActiveBookmark: false,
          src: "assets/media/Alma16.mp3",
        },
        {
          uuid: 117,
          bookID: 10,
          book: "Alma",
          chapter: 17,
          narrator: "Tera",
          narratorImageName: "Tera",
          chapterImageName: "Alma17",
          audioFileName: "Alma17",
          isActiveBookmark: false,
          src: "assets/media/Alma17.mp3",
        },
        {
          uuid: 118,
          bookID: 10,
          book: "Alma",
          chapter: 18,
          narrator: "Mya",
          narratorImageName: "Mya",
          chapterImageName: "Alma18",
          audioFileName: "Alma18",
          isActiveBookmark: false,
          src: "assets/media/Alma18.mp3",
        },
        {
          uuid: 119,
          bookID: 10,
          book: "Alma",
          chapter: 19,
          narrator: "Sara",
          narratorImageName: "Sara",
          chapterImageName: "BOMpic",
          audioFileName: "Alma19",
          isActiveBookmark: false,
          src: "assets/media/Alma19.mp3",
        },
        {
          uuid: 120,
          bookID: 10,
          book: "Alma",
          chapter: 20,
          narrator: "Nate",
          narratorImageName: "Nate",
          chapterImageName: "Alma20",
          audioFileName: "Alma20",
          isActiveBookmark: false,
          src: "assets/media/Alma20.mp3",
        },
        {
          uuid: 121,
          bookID: 10,
          book: "Alma",
          chapter: 21,
          narrator: "Sully",
          narratorImageName: "Sully",
          chapterImageName: "BOMpic",
          audioFileName: "Alma21",
          isActiveBookmark: false,
          src: "assets/media/Alma21.mp3",
        },
        {
          uuid: 122,
          bookID: 10,
          book: "Alma",
          chapter: 22,
          narrator: "Maren",
          narratorImageName: "Maren",
          chapterImageName: "BOMpic",
          audioFileName: "Alma22",
          isActiveBookmark: false,
          src: "assets/media/Alma22.mp3",
        },
        {
          uuid: 123,
          bookID: 10,
          book: "Alma",
          chapter: 23,
          narrator: "Abby",
          narratorImageName: "Abby",
          chapterImageName: "BOMpic",
          audioFileName: "Alma23",
          isActiveBookmark: false,
          src: "assets/media/Alma23.mp3",
        },
        {
          uuid: 124,
          bookID: 10,
          book: "Alma",
          chapter: 24,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "Alma24",
          audioFileName: "Alma24",
          isActiveBookmark: false,
          src: "assets/media/Alma24.mp3",
        },
        {
          uuid: 125,
          bookID: 10,
          book: "Alma",
          chapter: 25,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "Alma25",
          isActiveBookmark: false,
          src: "assets/media/Alma25.mp3",
        },
        {
          uuid: 126,
          bookID: 10,
          book: "Alma",
          chapter: 26,
          narrator: "Dugan",
          narratorImageName: "Dugan",
          chapterImageName: "Alma26",
          audioFileName: "Alma26",
          isActiveBookmark: false,
          src: "assets/media/Alma26.mp3",
        },
        {
          uuid: 127,
          bookID: 10,
          book: "Alma",
          chapter: 27,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "BOMpic",
          audioFileName: "Alma27",
          isActiveBookmark: false,
          src: "assets/media/Alma27.mp3",
        },
        {
          uuid: 128,
          bookID: 10,
          book: "Alma",
          chapter: 28,
          narrator: "Ali",
          narratorImageName: "Ali",
          chapterImageName: "BOMpic",
          audioFileName: "Alma28",
          isActiveBookmark: false,
          src: "assets/media/Alma28.mp3",
        },
        {
          uuid: 129,
          bookID: 10,
          book: "Alma",
          chapter: 29,
          narrator: "Maren",
          narratorImageName: "Maren",
          chapterImageName: "BOMpic",
          audioFileName: "Alma29",
          isActiveBookmark: false,
          src: "assets/media/Alma29.mp3",
        },
        {
          uuid: 130,
          bookID: 10,
          book: "Alma",
          chapter: 30,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "Alma30",
          audioFileName: "Alma30",
          isActiveBookmark: false,
          src: "assets/media/Alma30.mp3",
        },
        {
          uuid: 131,
          bookID: 10,
          book: "Alma",
          chapter: 31,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "Alma31",
          audioFileName: "Alma31",
          isActiveBookmark: false,
          src: "assets/media/Alma31.mp3",
        },
        {
          uuid: 132,
          bookID: 10,
          book: "Alma",
          chapter: 32,
          narrator: "Mya",
          narratorImageName: "Mya",
          chapterImageName: "Alma32",
          audioFileName: "Alma32",
          isActiveBookmark: false,
          src: "assets/media/Alma32.mp3",
        },
        {
          uuid: 133,
          bookID: 10,
          book: "Alma",
          chapter: 33,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "Alma33",
          isActiveBookmark: false,
          src: "assets/media/Alma33.mp3",
        },
        {
          uuid: 134,
          bookID: 10,
          book: "Alma",
          chapter: 34,
          narrator: "Greta",
          narratorImageName: "Greta",
          chapterImageName: "BOMpic",
          audioFileName: "Alma34",
          isActiveBookmark: false,
          src: "assets/media/Alma34.mp3",
        },
        {
          uuid: 135,
          bookID: 10,
          book: "Alma",
          chapter: 35,
          narrator: "Melissa",
          narratorImageName: "Melissa",
          chapterImageName: "BOMpic",
          audioFileName: "Alma35",
          isActiveBookmark: false,
          src: "assets/media/Alma35.mp3",
        },
        {
          uuid: 136,
          bookID: 10,
          book: "Alma",
          chapter: 36,
          narrator: "James",
          narratorImageName: "James",
          chapterImageName: "Alma36",
          audioFileName: "Alma36",
          isActiveBookmark: false,
          src: "assets/media/Alma36.mp3",
        },
        {
          uuid: 137,
          bookID: 10,
          book: "Alma",
          chapter: 37,
          narrator: "James",
          narratorImageName: "James",
          chapterImageName: "Alma37",
          audioFileName: "Alma37",
          isActiveBookmark: false,
          src: "assets/media/Alma37.mp3",
        },
        {
          uuid: 138,
          bookID: 10,
          book: "Alma",
          chapter: 38,
          narrator: "Lucie",
          narratorImageName: "Lucie",
          chapterImageName: "BOMpic",
          audioFileName: "Alma38",
          isActiveBookmark: false,
          src: "assets/media/Alma38.mp3",
        },
        {
          uuid: 139,
          bookID: 10,
          book: "Alma",
          chapter: 39,
          narrator: "Lucie",
          narratorImageName: "Lucie",
          chapterImageName: "BOMpic",
          audioFileName: "Alma39",
          isActiveBookmark: false,
          src: "assets/media/Alma39.mp3",
        },
        {
          uuid: 140,
          bookID: 10,
          book: "Alma",
          chapter: 40,
          narrator: "Dugan",
          narratorImageName: "Dugan",
          chapterImageName: "BOMpic",
          audioFileName: "Alma40",
          isActiveBookmark: false,
          src: "assets/media/Alma40.mp3",
        },
        {
          uuid: 141,
          bookID: 10,
          book: "Alma",
          chapter: 41,
          narrator: "Sully",
          narratorImageName: "Sully",
          chapterImageName: "BOMpic",
          audioFileName: "Alma41",
          isActiveBookmark: false,
          src: "assets/media/Alma41.mp3",
        },
        {
          uuid: 142,
          bookID: 10,
          book: "Alma",
          chapter: 42,
          narrator: "Scot",
          narratorImageName: "Scot",
          chapterImageName: "BOMpic",
          audioFileName: "Alma42",
          isActiveBookmark: false,
          src: "assets/media/Alma42.mp3",
        },
        {
          uuid: 143,
          bookID: 10,
          book: "Alma",
          chapter: 43,
          narrator: "Eric",
          narratorImageName: "Eric",
          chapterImageName: "Alma43",
          audioFileName: "Alma43",
          isActiveBookmark: false,
          src: "assets/media/Alma43.mp3",
        },
        {
          uuid: 144,
          bookID: 10,
          book: "Alma",
          chapter: 44,
          narrator: "Alan",
          narratorImageName: "Alan",
          chapterImageName: "Alma44",
          audioFileName: "Alma44",
          isActiveBookmark: false,
          src: "assets/media/Alma44.mp3",
        },
        {
          uuid: 145,
          bookID: 10,
          book: "Alma",
          chapter: 45,
          narrator: "Melissa",
          narratorImageName: "Melissa",
          chapterImageName: "BOMpic",
          audioFileName: "Alma45",
          isActiveBookmark: false,
          src: "assets/media/Alma45.mp3",
        },
        {
          uuid: 146,
          bookID: 10,
          book: "Alma",
          chapter: 46,
          narrator: "Will",
          narratorImageName: "Will",
          chapterImageName: "Alma46",
          audioFileName: "Alma46",
          isActiveBookmark: false,
          src: "assets/media/Alma46.mp3",
        },
        {
          uuid: 147,
          bookID: 10,
          book: "Alma",
          chapter: 47,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "BOMpic",
          audioFileName: "Alma47",
          isActiveBookmark: false,
          src: "assets/media/Alma47.mp3",
        },
        {
          uuid: 148,
          bookID: 10,
          book: "Alma",
          chapter: 48,
          narrator: "Britta",
          narratorImageName: "Britta",
          chapterImageName: "BOMpic",
          audioFileName: "Alma48",
          isActiveBookmark: false,
          src: "assets/media/Alma48.mp3",
        },
        {
          uuid: 149,
          bookID: 10,
          book: "Alma",
          chapter: 49,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "BOMpic",
          audioFileName: "Alma49",
          isActiveBookmark: false,
          src: "assets/media/Alma49.mp3",
        },
        {
          uuid: 150,
          bookID: 10,
          book: "Alma",
          chapter: 50,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "Alma50",
          isActiveBookmark: false,
          src: "assets/media/Alma50.mp3",
        },
        {
          uuid: 151,
          bookID: 10,
          book: "Alma",
          chapter: 51,
          narrator: "Lars",
          narratorImageName: "Lars",
          chapterImageName: "BOMpic",
          audioFileName: "Alma51",
          isActiveBookmark: false,
          src: "assets/media/Alma51.mp3",
        },
        {
          uuid: 152,
          bookID: 10,
          book: "Alma",
          chapter: 52,
          narrator: "Nate",
          narratorImageName: "Nate",
          chapterImageName: "BOMpic",
          audioFileName: "Alma52",
          isActiveBookmark: false,
          src: "assets/media/Alma52.mp3",
        },
        {
          uuid: 153,
          bookID: 10,
          book: "Alma",
          chapter: 53,
          narrator: "Chloe",
          narratorImageName: "Chloe",
          chapterImageName: "Alma53",
          audioFileName: "Alma53",
          isActiveBookmark: false,
          src: "assets/media/Alma53.mp3",
        },
        {
          uuid: 154,
          bookID: 10,
          book: "Alma",
          chapter: 54,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "BOMpic",
          audioFileName: "Alma54",
          isActiveBookmark: false,
          src: "assets/media/Alma54.mp3",
        },
        {
          uuid: 155,
          bookID: 10,
          book: "Alma",
          chapter: 55,
          narrator: "Brinton",
          narratorImageName: "Brinton",
          chapterImageName: "BOMpic",
          audioFileName: "Alma55",
          isActiveBookmark: false,
          src: "assets/media/Alma55.mp3",
        },
        {
          uuid: 156,
          bookID: 10,
          book: "Alma",
          chapter: 56,
          narrator: "Julie T",
          narratorImageName: "JulieT",
          chapterImageName: "BOMpic",
          audioFileName: "Alma56",
          isActiveBookmark: false,
          src: "assets/media/Alma56.mp3",
        },
        {
          uuid: 157,
          bookID: 10,
          book: "Alma",
          chapter: 57,
          narrator: "Mitchell",
          narratorImageName: "Mitchell",
          chapterImageName: "BOMpic",
          audioFileName: "Alma57",
          isActiveBookmark: false,
          src: "assets/media/Alma57.mp3",
        },
        {
          uuid: 158,
          bookID: 10,
          book: "Alma",
          chapter: 58,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "BOMpic",
          audioFileName: "Alma58",
          isActiveBookmark: false,
          src: "assets/media/Alma58.mp3",
        },
        {
          uuid: 159,
          bookID: 10,
          book: "Alma",
          chapter: 59,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "BOMpic",
          audioFileName: "Alma59",
          isActiveBookmark: false,
          src: "assets/media/Alma59.mp3",
        },
        {
          uuid: 160,
          bookID: 10,
          book: "Alma",
          chapter: 60,
          narrator: "Sully",
          narratorImageName: "Sully",
          chapterImageName: "BOMpic",
          audioFileName: "Alma60",
          isActiveBookmark: false,
          src: "assets/media/Alma60.mp3",
        },
        {
          uuid: 161,
          bookID: 10,
          book: "Alma",
          chapter: 61,
          narrator: "Carley",
          narratorImageName: "Carley",
          chapterImageName: "BOMpic",
          audioFileName: "Alma61",
          isActiveBookmark: false,
          src: "assets/media/Alma61.mp3",
        },
        {
          uuid: 162,
          bookID: 10,
          book: "Alma",
          chapter: 62,
          narrator: "Will",
          narratorImageName: "Will",
          chapterImageName: "BOMpic",
          audioFileName: "Alma62",
          isActiveBookmark: false,
          src: "assets/media/Alma62.mp3",
        },
        {
          uuid: 163,
          bookID: 10,
          book: "Alma",
          chapter: 63,
          narrator: "Kate",
          narratorImageName: "Kate",
          chapterImageName: "BOMpic",
          audioFileName: "Alma63",
          isActiveBookmark: false,
          src: "assets/media/Alma63.mp3",
        },
        {
          uuid: 164,
          bookID: 11,
          book: "Helaman",
          chapter: 1,
          narrator: "Mya",
          narratorImageName: "Mya",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman1",
          isActiveBookmark: false,
          src: "assets/media/Helaman1.mp3",
        },
        {
          uuid: 165,
          bookID: 11,
          book: "Helaman",
          chapter: 2,
          narrator: "Sara",
          narratorImageName: "Sara",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman2",
          isActiveBookmark: false,
          src: "assets/media/Helaman2.mp3",
        },
        {
          uuid: 166,
          bookID: 11,
          book: "Helaman",
          chapter: 3,
          narrator: "Carley",
          narratorImageName: "Carley",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman3",
          isActiveBookmark: false,
          src: "assets/media/Helaman3.mp3",
        },
        {
          uuid: 167,
          bookID: 11,
          book: "Helaman",
          chapter: 4,
          narrator: "Ali",
          narratorImageName: "Ali",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman4",
          isActiveBookmark: false,
          src: "assets/media/Helaman4.mp3",
        },
        {
          uuid: 168,
          bookID: 11,
          book: "Helaman",
          chapter: 5,
          narrator: "Eric",
          narratorImageName: "Eric",
          chapterImageName: "Helaman5",
          audioFileName: "Helaman5",
          isActiveBookmark: false,
          src: "assets/media/Helaman5.mp3",
        },
        {
          uuid: 169,
          bookID: 11,
          book: "Helaman",
          chapter: 6,
          narrator: "Scot",
          narratorImageName: "Scot",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman6",
          isActiveBookmark: false,
          src: "assets/media/Helaman6.mp3",
        },
        {
          uuid: 170,
          bookID: 11,
          book: "Helaman",
          chapter: 7,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman7",
          isActiveBookmark: false,
          src: "assets/media/Helaman7.mp3",
        },
        {
          uuid: 171,
          bookID: 11,
          book: "Helaman",
          chapter: 8,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman8",
          isActiveBookmark: false,
          src: "assets/media/Helaman8.mp3",
        },
        {
          uuid: 172,
          bookID: 11,
          book: "Helaman",
          chapter: 9,
          narrator: "Susan",
          narratorImageName: "Susan",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman9",
          isActiveBookmark: false,
          src: "assets/media/Helaman9.mp3",
        },
        {
          uuid: 173,
          bookID: 11,
          book: "Helaman",
          chapter: 10,
          narrator: "Nels",
          narratorImageName: "Nels",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman10",
          isActiveBookmark: false,
          src: "assets/media/Helaman10.mp3",
        },
        {
          uuid: 174,
          bookID: 11,
          book: "Helaman",
          chapter: 11,
          narrator: "Melissa",
          narratorImageName: "Melissa",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman11",
          isActiveBookmark: false,
          src: "assets/media/Helaman11.mp3",
        },
        {
          uuid: 175,
          bookID: 11,
          book: "Helaman",
          chapter: 12,
          narrator: "Lars",
          narratorImageName: "Lars",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman12",
          isActiveBookmark: false,
          src: "assets/media/Helaman12.mp3",
        },
        {
          uuid: 176,
          bookID: 11,
          book: "Helaman",
          chapter: 13,
          narrator: "Scot",
          narratorImageName: "Scot",
          chapterImageName: "Helaman13",
          audioFileName: "Helaman13",
          isActiveBookmark: false,
          src: "assets/media/Helaman13.mp3",
        },
        {
          uuid: 177,
          bookID: 11,
          book: "Helaman",
          chapter: 14,
          narrator: "Scot",
          narratorImageName: "Scot",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman14",
          isActiveBookmark: false,
          src: "assets/media/Helaman14.mp3",
        },
        {
          uuid: 178,
          bookID: 11,
          book: "Helaman",
          chapter: 15,
          narrator: "Scot",
          narratorImageName: "Scot",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman15",
          isActiveBookmark: false,
          src: "assets/media/Helaman15.mp3",
        },
        {
          uuid: 179,
          bookID: 11,
          book: "Helaman",
          chapter: 16,
          narrator: "Anika",
          narratorImageName: "Anika",
          chapterImageName: "BOMpic",
          audioFileName: "Helaman16",
          isActiveBookmark: false,
          src: "assets/media/Helaman16.mp3",
        },
        {
          uuid: 180,
          bookID: 12,
          book: "3 Nephi",
          chapter: 1,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi1",
          isActiveBookmark: false,
          src: "assets/media/3Nephi1.mp3",
        },
        {
          uuid: 181,
          bookID: 12,
          book: "3 Nephi",
          chapter: 2,
          narrator: "Sara",
          narratorImageName: "Sara",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi2",
          isActiveBookmark: false,
          src: "assets/media/3Nephi2.mp3",
        },
        {
          uuid: 182,
          bookID: 12,
          book: "3 Nephi",
          chapter: 3,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi3",
          isActiveBookmark: false,
          src: "assets/media/3Nephi3.mp3",
        },
        {
          uuid: 183,
          bookID: 12,
          book: "3 Nephi",
          chapter: 4,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi4",
          isActiveBookmark: false,
          src: "assets/media/3Nephi4.mp3",
        },
        {
          uuid: 184,
          bookID: 12,
          book: "3 Nephi",
          chapter: 5,
          narrator: "Eric",
          narratorImageName: "Eric",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi5",
          isActiveBookmark: false,
          src: "assets/media/3Nephi5.mp3",
        },
        {
          uuid: 185,
          bookID: 12,
          book: "3 Nephi",
          chapter: 6,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi6",
          isActiveBookmark: false,
          src: "assets/media/3Nephi6.mp3",
        },
        {
          uuid: 186,
          bookID: 12,
          book: "3 Nephi",
          chapter: 7,
          narrator: "Sully",
          narratorImageName: "Sully",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi7",
          isActiveBookmark: false,
          src: "assets/media/3Nephi7.mp3",
        },
        {
          uuid: 187,
          bookID: 12,
          book: "3 Nephi",
          chapter: 8,
          narrator: "Susan",
          narratorImageName: "Susan",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi8",
          isActiveBookmark: false,
          src: "assets/media/3Nephi8.mp3",
        },
        {
          uuid: 188,
          bookID: 12,
          book: "3 Nephi",
          chapter: 9,
          narrator: "Susan",
          narratorImageName: "Susan",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi9",
          isActiveBookmark: false,
          src: "assets/media/3Nephi9.mp3",
        },
        {
          uuid: 189,
          bookID: 12,
          book: "3 Nephi",
          chapter: 10,
          narrator: "Britta",
          narratorImageName: "Britta",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi10",
          isActiveBookmark: false,
          src: "assets/media/3Nephi10.mp3",
        },
        {
          uuid: 190,
          bookID: 12,
          book: "3 Nephi",
          chapter: 11,
          narrator: "Julie W",
          narratorImageName: "JulieW",
          chapterImageName: "3Nephi11",
          audioFileName: "3Nephi11",
          isActiveBookmark: false,
          src: "assets/media/3Nephi11.mp3",
        },
        {
          uuid: 191,
          bookID: 12,
          book: "3 Nephi",
          chapter: 12,
          narrator: "Melissa",
          narratorImageName: "Melissa",
          chapterImageName: "3Nephi12",
          audioFileName: "3Nephi12",
          isActiveBookmark: false,
          src: "assets/media/3Nephi12.mp3",
        },
        {
          uuid: 192,
          bookID: 12,
          book: "3 Nephi",
          chapter: 13,
          narrator: "Brinton",
          narratorImageName: "Brinton",
          chapterImageName: "3Nephi13",
          audioFileName: "3Nephi13",
          isActiveBookmark: false,
          src: "assets/media/3Nephi13.mp3",
        },
        {
          uuid: 193,
          bookID: 12,
          book: "3 Nephi",
          chapter: 14,
          narrator: "Brinton",
          narratorImageName: "Brinton",
          chapterImageName: "3Nephi14",
          audioFileName: "3Nephi14",
          isActiveBookmark: false,
          src: "assets/media/3Nephi14.mp3",
        },
        {
          uuid: 194,
          bookID: 12,
          book: "3 Nephi",
          chapter: 15,
          narrator: "Maren",
          narratorImageName: "Maren",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi15",
          isActiveBookmark: false,
          src: "assets/media/3Nephi15.mp3",
        },
        {
          uuid: 195,
          bookID: 12,
          book: "3 Nephi",
          chapter: 16,
          narrator: "Abby",
          narratorImageName: "Abby",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi16",
          isActiveBookmark: false,
          src: "assets/media/3Nephi16.mp3",
        },
        {
          uuid: 196,
          bookID: 12,
          book: "3 Nephi",
          chapter: 17,
          narrator: "Kate",
          narratorImageName: "Kate",
          chapterImageName: "3Nephi17",
          audioFileName: "3Nephi17",
          isActiveBookmark: false,
          src: "assets/media/3Nephi17.mp3",
        },
        {
          uuid: 197,
          bookID: 12,
          book: "3 Nephi",
          chapter: 18,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi18",
          isActiveBookmark: false,
          src: "assets/media/3Nephi18.mp3",
        },
        {
          uuid: 198,
          bookID: 12,
          book: "3 Nephi",
          chapter: 19,
          narrator: "Carol",
          narratorImageName: "Carol",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi19",
          isActiveBookmark: false,
          src: "assets/media/3Nephi19.mp3",
        },
        {
          uuid: 199,
          bookID: 12,
          book: "3 Nephi",
          chapter: 20,
          narrator: "Julie W",
          narratorImageName: "JulieW",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi20",
          isActiveBookmark: false,
          src: "assets/media/3Nephi20.mp3",
        },
        {
          uuid: 200,
          bookID: 12,
          book: "3 Nephi",
          chapter: 21,
          narrator: "Greta",
          narratorImageName: "Greta",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi21",
          isActiveBookmark: false,
          src: "assets/media/3Nephi21.mp3",
        },
        {
          uuid: 201,
          bookID: 12,
          book: "3 Nephi",
          chapter: 22,
          narrator: "Sadie",
          narratorImageName: "Sadie",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi22",
          isActiveBookmark: false,
          src: "assets/media/3Nephi22.mp3",
        },
        {
          uuid: 202,
          bookID: 12,
          book: "3 Nephi",
          chapter: 23,
          narrator: "Sadie",
          narratorImageName: "Sadie",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi23",
          isActiveBookmark: false,
          src: "assets/media/3Nephi23.mp3",
        },
        {
          uuid: 203,
          bookID: 12,
          book: "3 Nephi",
          chapter: 24,
          narrator: "Nate",
          narratorImageName: "Nate",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi24",
          isActiveBookmark: false,
          src: "assets/media/3Nephi24.mp3",
        },
        {
          uuid: 204,
          bookID: 12,
          book: "3 Nephi",
          chapter: 25,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi25",
          isActiveBookmark: false,
          src: "assets/media/3Nephi25.mp3",
        },
        {
          uuid: 205,
          bookID: 12,
          book: "3 Nephi",
          chapter: 26,
          narrator: "Abby",
          narratorImageName: "Abby",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi26",
          isActiveBookmark: false,
          src: "assets/media/3Nephi26.mp3",
        },
        {
          uuid: 206,
          bookID: 12,
          book: "3 Nephi",
          chapter: 27,
          narrator: "Chloe",
          narratorImageName: "Chloe",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi27",
          isActiveBookmark: false,
          src: "assets/media/3Nephi27.mp3",
        },
        {
          uuid: 207,
          bookID: 12,
          book: "3 Nephi",
          chapter: 28,
          narrator: "Dugan",
          narratorImageName: "Dugan",
          chapterImageName: "3Nephi28",
          audioFileName: "3Nephi28",
          isActiveBookmark: false,
          src: "assets/media/3Nephi28.mp3",
        },
        {
          uuid: 208,
          bookID: 12,
          book: "3 Nephi",
          chapter: 29,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi29",
          isActiveBookmark: false,
          src: "assets/media/3Nephi29.mp3",
        },
        {
          uuid: 209,
          bookID: 12,
          book: "3 Nephi",
          chapter: 30,
          narrator: "Kate",
          narratorImageName: "Kate",
          chapterImageName: "BOMpic",
          audioFileName: "3Nephi30",
          isActiveBookmark: false,
          src: "assets/media/3Nephi30.mp3",
        },
        {
          uuid: 210,
          bookID: 13,
          book: "4 Nephi",
          chapter: 1,
          narrator: "Mya",
          narratorImageName: "Mya",
          chapterImageName: "BOMpic",
          audioFileName: "4Nephi1",
          isActiveBookmark: false,
          src: "assets/media/4Nephi1.mp3",
        },
        {
          uuid: 211,
          bookID: 14,
          book: "Mormon",
          chapter: 1,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "Mormon1",
          audioFileName: "Mormon1",
          isActiveBookmark: false,
          src: "assets/media/Mormon1.mp3",
        },
        {
          uuid: 212,
          bookID: 14,
          book: "Mormon",
          chapter: 2,
          narrator: "Eric",
          narratorImageName: "Eric",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon2",
          isActiveBookmark: false,
          src: "assets/media/Mormon2.mp3",
        },
        {
          uuid: 213,
          bookID: 14,
          book: "Mormon",
          chapter: 3,
          narrator: "Lucie",
          narratorImageName: "Lucie",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon3",
          isActiveBookmark: false,
          src: "assets/media/Mormon3.mp3",
        },
        {
          uuid: 214,
          bookID: 14,
          book: "Mormon",
          chapter: 4,
          narrator: "Julie W",
          narratorImageName: "JulieW",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon4",
          isActiveBookmark: false,
          src: "assets/media/Mormon4.mp3",
        },
        {
          uuid: 215,
          bookID: 14,
          book: "Mormon",
          chapter: 5,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "Mormon5",
          audioFileName: "Mormon5",
          isActiveBookmark: false,
          src: "assets/media/Mormon5.mp3",
        },
        {
          uuid: 216,
          bookID: 14,
          book: "Mormon",
          chapter: 6,
          narrator: "Mitch",
          narratorImageName: "Mitch",
          chapterImageName: "Mormon6",
          audioFileName: "Mormon6",
          isActiveBookmark: false,
          src: "assets/media/Mormon6.mp3",
        },
        {
          uuid: 217,
          bookID: 14,
          book: "Mormon",
          chapter: 7,
          narrator: "Ali",
          narratorImageName: "Ali",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon7",
          isActiveBookmark: false,
          src: "assets/media/Mormon7.mp3",
        },
        {
          uuid: 218,
          bookID: 14,
          book: "Mormon",
          chapter: 8,
          narrator: "Nels",
          narratorImageName: "Nels",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon8",
          isActiveBookmark: false,
          src: "assets/media/Mormon8.mp3",
        },
        {
          uuid: 219,
          bookID: 14,
          book: "Mormon",
          chapter: 9,
          narrator: "Jim",
          narratorImageName: "Jim",
          chapterImageName: "BOMpic",
          audioFileName: "Mormon9",
          isActiveBookmark: false,
          src: "assets/media/Mormon9.mp3",
        },
        {
          uuid: 220,
          bookID: 15,
          book: "Ether",
          chapter: 1,
          narrator: "Kurt",
          narratorImageName: "Kurt",
          chapterImageName: "Ether1",
          audioFileName: "Ether1",
          isActiveBookmark: false,
          src: "assets/media/Ether1.mp3",
        },
        {
          uuid: 221,
          bookID: 15,
          book: "Ether",
          chapter: 2,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "Ether2",
          audioFileName: "Ether2",
          isActiveBookmark: false,
          src: "assets/media/Ether2.mp3",
        },
        {
          uuid: 222,
          bookID: 15,
          book: "Ether",
          chapter: 3,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "Ether3",
          audioFileName: "Ether3",
          isActiveBookmark: false,
          src: "assets/media/Ether3.mp3",
        },
        {
          uuid: 223,
          bookID: 15,
          book: "Ether",
          chapter: 4,
          narrator: "Eric",
          narratorImageName: "Eric",
          chapterImageName: "BOMpic",
          audioFileName: "Ether4",
          isActiveBookmark: false,
          src: "assets/media/Ether4.mp3",
        },
        {
          uuid: 224,
          bookID: 15,
          book: "Ether",
          chapter: 5,
          narrator: "Benn",
          narratorImageName: "Benn",
          chapterImageName: "BOMpic",
          audioFileName: "Ether5",
          isActiveBookmark: false,
          src: "assets/media/Ether5.mp3",
        },
        {
          uuid: 225,
          bookID: 15,
          book: "Ether",
          chapter: 6,
          narrator: "Britta",
          narratorImageName: "Britta",
          chapterImageName: "BOMpic",
          audioFileName: "Ether6",
          isActiveBookmark: false,
          src: "assets/media/Ether6.mp3",
        },
        {
          uuid: 226,
          bookID: 15,
          book: "Ether",
          chapter: 7,
          narrator: "Greta",
          narratorImageName: "Greta",
          chapterImageName: "BOMpic",
          audioFileName: "Ether7",
          isActiveBookmark: false,
          src: "assets/media/Ether7.mp3",
        },
        {
          uuid: 227,
          bookID: 15,
          book: "Ether",
          chapter: 8,
          narrator: "Lexy",
          narratorImageName: "Lexy",
          chapterImageName: "BOMpic",
          audioFileName: "Ether8",
          isActiveBookmark: false,
          src: "assets/media/Ether8.mp3",
        },
        {
          uuid: 228,
          bookID: 15,
          book: "Ether",
          chapter: 9,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "Ether9",
          isActiveBookmark: false,
          src: "assets/media/Ether9.mp3",
        },
        {
          uuid: 229,
          bookID: 15,
          book: "Ether",
          chapter: 10,
          narrator: "Anika",
          narratorImageName: "Anika",
          chapterImageName: "BOMpic",
          audioFileName: "Ether10",
          isActiveBookmark: false,
          src: "assets/media/Ether10.mp3",
        },
        {
          uuid: 230,
          bookID: 15,
          book: "Ether",
          chapter: 11,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "BOMpic",
          audioFileName: "Ether11",
          isActiveBookmark: false,
          src: "assets/media/Ether11.mp3",
        },
        {
          uuid: 231,
          bookID: 15,
          book: "Ether",
          chapter: 12,
          narrator: "Abby",
          narratorImageName: "Abby",
          chapterImageName: "BOMpic",
          audioFileName: "Ether12",
          isActiveBookmark: false,
          src: "assets/media/Ether12.mp3",
        },
        {
          uuid: 232,
          bookID: 15,
          book: "Ether",
          chapter: 13,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "BOMpic",
          audioFileName: "Ether13",
          isActiveBookmark: false,
          src: "assets/media/Ether13.mp3",
        },
        {
          uuid: 233,
          bookID: 15,
          book: "Ether",
          chapter: 14,
          narrator: "Gina",
          narratorImageName: "Gina",
          chapterImageName: "BOMpic",
          audioFileName: "Ether14",
          isActiveBookmark: false,
          src: "assets/media/Ether14.mp3",
        },
        {
          uuid: 234,
          bookID: 15,
          book: "Ether",
          chapter: 15,
          narrator: "Sara",
          narratorImageName: "Sara",
          chapterImageName: "BOMpic",
          audioFileName: "Ether15",
          isActiveBookmark: false,
          src: "assets/media/Ether15.mp3",
        },
        {
          uuid: 235,
          bookID: 16,
          book: "Moroni",
          chapter: 1,
          narrator: "Benn",
          narratorImageName: "Benn",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni1",
          isActiveBookmark: false,
          src: "assets/media/Moroni1.mp3",
        },
        {
          uuid: 236,
          bookID: 16,
          book: "Moroni",
          chapter: 2,
          narrator: "Kate",
          narratorImageName: "Kate",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni2",
          isActiveBookmark: false,
          src: "assets/media/Moroni2.mp3",
        },
        {
          uuid: 237,
          bookID: 16,
          book: "Moroni",
          chapter: 3,
          narrator: "Gunnar",
          narratorImageName: "Gunnar",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni3",
          isActiveBookmark: false,
          src: "assets/media/Moroni3.mp3",
        },
        {
          uuid: 238,
          bookID: 16,
          book: "Moroni",
          chapter: 4,
          narrator: "Alan",
          narratorImageName: "Alan",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni4",
          isActiveBookmark: false,
          src: "assets/media/Moroni4.mp3",
        },
        {
          uuid: 239,
          bookID: 16,
          book: "Moroni",
          chapter: 5,
          narrator: "Alan",
          narratorImageName: "Alan",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni5",
          isActiveBookmark: false,
          src: "assets/media/Moroni5.mp3",
        },
        {
          uuid: 240,
          bookID: 16,
          book: "Moroni",
          chapter: 6,
          narrator: "Loree",
          narratorImageName: "Loree",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni6",
          isActiveBookmark: false,
          src: "assets/media/Moroni6.mp3",
        },
        {
          uuid: 241,
          bookID: 16,
          book: "Moroni",
          chapter: 7,
          narrator: "Julie T",
          narratorImageName: "JulieT",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni7",
          isActiveBookmark: false,
          src: "assets/media/Moroni7.mp3",
        },
        {
          uuid: 242,
          bookID: 16,
          book: "Moroni",
          chapter: 8,
          narrator: "Chloe",
          narratorImageName: "Chloe",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni8",
          isActiveBookmark: false,
          src: "assets/media/Moroni8.mp3",
        },
        {
          uuid: 243,
          bookID: 16,
          book: "Moroni",
          chapter: 9,
          narrator: "Maren",
          narratorImageName: "Maren",
          chapterImageName: "BOMpic",
          audioFileName: "Moroni9",
          isActiveBookmark: false,
          src: "assets/media/Moroni9.mp3",
        },
        {
          uuid: 244,
          bookID: 16,
          book: "Moroni",
          chapter: 10,
          narrator: "Jedd",
          narratorImageName: "Jedd",
          chapterImageName: "Moroni10",
          audioFileName: "Moroni10",
          isActiveBookmark: false,
          src: "assets/media/Moroni10.mp3",
        },
      ],
    };
  },
  beforeUpdate() {
    this.currentImage = "./assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
    this.index = this.selectedReader.uuid - 1; //reset the index
  },
  mounted() {
    this.determineUserAndReader();
    this.currentImage =
      "./assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
    this.index = this.selectedReader.uuid - 1;
    this.audio.src = this.selectedReader.src;
    this.audio.volume = this.volume / 100;
    this.progressBar = document.querySelector("#progressBar");
    this.progressBar.value = 0;
    this.initProgress();
  },
  methods: {
    determineUserAndReader() {
      const user1 = usePage().props.value.auth.user;
      const theReader = this.readers.filter(
        (reader) => reader.uuid === user1.uuid
      );
      this.updateSelectedReader(theReader[0]);
    },
    initProgress() {
      this.audio.addEventListener("loadedmetadata", () => {
        this.currentDuration = this.audio.duration;
        let secs = `${parseInt(`${this.currentDuration % 60}`, 10)}`.padStart(
          2,
          "0"
        );
        let mins = parseInt(`${(this.currentDuration / 60) % 60}`, 10);
        this.currentDurationTxt = `${mins}:${secs}`;
        this.progressBar.max = this.currentDuration;
      });
      this.audio.addEventListener("timeupdate", () => {
        this.updateProgress(this.audio.currentTime);
      });
    },
    updateProgress(time) {
      this.progressBar.value = time;
      let secs = `${parseInt(`${time % 60}`, 10)}`.padStart(2, "0");
      let mins = parseInt(`${(time / 60) % 60}`, 10);
      this.currentTimeTxt = `${mins}:${secs}`;
    },
    updateVolume() {
      this.audio.volume = this.volume / 100;
      this.isMuted = false;
      if (this.volume >= 100) {
        this.isMaxed = true;
        this.isMuted = false;
      } else if (this.volume <= 0) {
        this.isMaxed = false;
        this.isMuted = true;
      }
    },
    mute() {
      this.isMuted = true;
      this.isMaxed = false;
      this.volume = 0;
      this.audio.volume = 0;
    },
    max() {
      this.isMaxed = true;
      this.isMuted = false;
      this.volume = 100;
      this.audio.volume = this.volume / 100;
    },
    play(reader) {
      // ????????
      // If the current image has changed, stop playing
      // => Trying to stop play when menu has selected a new reader

      if (typeof reader.src != "undefined") {
        this.audio.src = this.selectedReader.src;
      }
      this.audio.src = this.selectedReader.src;
      this.index = this.selectedReader.uuid - 1;
      this.audio.play();
      this.isPlaying = true;
    },
    pause() {
      // console.log("pause");
      this.audio.pause();
      this.isPlaying = false;
    },
    next() {
      this.index++; //index is the location in readers array. It is equal to uuid-1.
      this.index > this.readers.length - 1 ? (this.index = 5) : this.index; //returns to 1 Nefi 1
      this.updateSelectedReader(this.readers[this.index]);
      this.play(this.selectedReader.src);
      this.currentImage =
        "assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
      // console.log("The current selected reader uuid is:",this.selectedReader.uuid)
      const user1 = usePage().props.value.auth.user;
      axios.put(
        route("reader", { uuid: this.selectedReader.uuid, user_id: user1.id })
      );
    },
    prev() {
      this.index--;
      this.index < 0 ? (this.index = 5) : this.index; //returns to 1 Nefi 1
      this.updateSelectedReader(this.readers[this.index]);
      this.play(this.selectedReader.src);
      this.currentImage =
        "assets/photos/" + this.selectedReader.narratorImageName + ".jpg";
      const user1 = usePage().props.value.auth.user;
      axios.put(
        route("reader", { uuid: this.selectedReader.uuid, user_id: user1.id })
      );
    },
    updateSelectedReader(reader) {
      //not sure why this is necessary, as this.selectedReader = reader should work, but it does not.
      this.selectedReader.uuid = reader.uuid;
      this.selectedReader.bookID = reader.bookID;
      this.selectedReader.book = reader.book;
      this.selectedReader.chapter = reader.chapter;
      this.selectedReader.narrator = reader.narrator;
      this.selectedReader.narratorImageName = reader.narratorImageName;
      this.selectedReader.chapterImageName = reader.chapterImageName;
      this.selectedReader.audioFileName = reader.audioFileName;
      this.selectedReader.isActiveBookmark = reader.isActiveBookmark;
      this.selectedReader.src = reader.src;
    },
  },
};
</script>